---
kind: Service
apiVersion: v1
metadata:
  name: test-service
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
status:
  loadBalancer: {}
